/* Created by relating with 8-bit array multiplier */
module am_32_bit (
  input [31:0] M, Q, //multiplicand, multiplier
  output [63:0] r
);
  wire ss[0:29][0:30]; //sums - generated by HAs or FAs
  wire cs[0:30][0:31]; //carries - generated by HAs or FAs
  wire pp[0:31][0:31]; //partial products - generated by AND combination individual bits of M, and Q

  genvar i, j, k;

  //generating partial products first p[i][j] = M[i] & Q[j]
  generate
    for (i = 0; i < 32; i = i + 1) begin : g1
      for (j = 0; j < 32; j = j + 1) begin : g2
        assign pp[i][j] = M[i] & Q[j];
      end
    end
  endgenerate

  assign r[0] = pp[0][0];
  half_adder h1(.S(r[1]), .C(cs[0][0]), .x(pp[1][0]), .y(pp[0][1]));

  generate
    for (i = 2; i < 32; i = i + 1) begin : g3
      full_adder f1(.S(ss[0][i-2]), .C(cs[0][i-1]), .x(pp[i][0]), .y(pp[i-1][1]), .z(cs[0][i-2]));
    end
  endgenerate
  
  half_adder h2(.S(ss[0][30]), .C(cs[0][31]), .x(cs[0][30]), .y(pp[31][1]));
  
  generate
    for (i = 2; i < 31; i = i + 1) begin : g4
      full_adder h1(.S(ss[i-1][30]), .C(cs[i-1][31]), .x(cs[i-1][30]), .y(cs[i-2][31]), .z(pp[31][i]));
    end
  endgenerate
  
  full_adder f1(.S(r[62]), .C(r[63]), .x(cs[29][31]), .y(cs[30][30]), .z(pp[31][31])); //seems correct

  generate
    for (i = 2; i < 32; i = i + 1) begin : g5
      half_adder h1(.S(r[i]), .C(cs[i-1][0]), .x(ss[i-2][0]), .y(pp[0][i]));
    end
  endgenerate

  generate
    for (i = 2; i < 31; i = i + 1) begin : g6
      for (j = 1; j < 31; j = j + 1) begin : g7
        full_adder f1(.S(ss[i-1][j-1]), .C(cs[i-1][j]), .x(ss[i-2][j]), .y(cs[i-1][j-1]), .z(pp[j][i]));
      end
    end
  endgenerate
  
  generate
    for (i = 1; i < 31; i = i + 1) begin : g8
      full_adder f1(.S(r[31+i]), .C(cs[30][i]), .x(cs[30][i-1]), .y(ss[29][i]), .z(pp[i][31]));
    end
  endgenerate
endmodule
