/* WARNING: Do not read this code without the reference diagram; you may get a migraine. */
module am_8_bit (
  input [7:0] M, Q, //multiplicand, multiplier
  output [15:0] r
);
  wire ss[0:5][0:6]; //sums - generated by HAs or FAs
  wire cs[0:6][0:7]; //carries - generated by HAs or FAs
  wire pp[0:7][0:7]; //partial products - generated by AND combination individual bits of M, and Q

  genvar i, j, k;

  //generating partial products first p[i][j] = M[i] & Q[j]
  generate
    for (i = 0; i < 8; i = i + 1) begin : g1
      for (j = 0; j < 8; j = j + 1) begin : g2
        assign pp[i][j] = M[i] & Q[j];
      end
    end
  endgenerate

  assign r[0] = pp[0][0];
  half_adder h1(.S(r[1]), .C(cs[0][0]), .x(pp[1][0]), .y(pp[0][1]));

  generate //seems correct
    for (i = 2; i < 8; i = i + 1) begin : g3
      full_adder f1(.S(ss[0][i-2]), .C(cs[0][i-1]), .x(pp[i][0]), .y(pp[i-1][1]), .z(cs[0][i-2]));
    end
  endgenerate
  
  half_adder h2(.S(ss[0][6]), .C(cs[0][7]), .x(cs[0][6]), .y(pp[7][1]));

  generate //seems correct
    for (i = 2; i < 7; i = i + 1) begin : g4
      full_adder f1(.S(ss[i-1][6]), .C(cs[i-1][7]), .x(cs[i-1][6]), .y(cs[i-2][7]), .z(pp[7][i]));
    end
  endgenerate
  
  full_adder f1(.S(r[14]), .C(r[15]), .x(cs[5][7]), .y(cs[6][6]), .z(pp[7][7])); //seems correct

  generate //seems correct
    for (i = 2; i < 8; i = i + 1) begin : g5
      half_adder h1(.S(r[i]), .C(cs[i-1][0]), .x(ss[i-2][0]), .y(pp[0][i]));
    end
  endgenerate

  generate //seems correct
    for (i = 2; i < 7; i = i + 1) begin : g6
      for (j = 1; j < 7; j = j + 1) begin : g7
        full_adder f1(.S(ss[i-1][j-1]), .C(cs[i-1][j]), .x(ss[i-2][j]), .y(cs[i-1][j-1]), .z(pp[j][i]));
      end
    end
  endgenerate
  
  generate //seems correct
    for (i = 1; i < 7; i = i + 1) begin : g8
      full_adder f1(.S(r[7+i]), .C(cs[6][i]), .x(cs[6][i-1]), .y(ss[5][i]), .z(pp[i][7]));
    end
  endgenerate
endmodule

